<?php
    include_once dirname(__DIR__) . '\\Types\\Penguin.php';


    $penguins = array();
    array_push($penguins, new Penguin("Adelie Penguin", "Pygoscelis adeliae", "krill", "No penguin, indeed no other bird, breeds further south than Adelie Penguins. Adelie Penguins show a number of specialised adaptations to the cold often encountered by this species that restrict heat loss.", "http://www.penguinworld.com/types/adelie_files/adeliel-2.jpg", 1));
    array_push($penguins, new Penguin("African Penguin", "Spheniscus demersus", "krill", "This is the only penguin breeding in Africa and was probably the first penguin encountered by Europeans. Numbers declined significantly during the Twentieth Century and their future has been jeopardized recently by major oil spills.", "http://www.penguinworld.com/types/african_files/africanl-2.jpg", 2));
    array_push($penguins, new Penguin("Chinstrap Penguin", "Pygoscelis antarctica", "krill", "This delicately coloured bird is arguably the most beautiful of penguins. In contrast to other adult penguins, apart from Royal Penguins, this species has a white face. This is separated from the white belly by a thin dark line running under the lower part of the chin - therefore the name.", "http://www.penguinworld.com/types/chinstrap_files/chinstrapl-2.jpg",3));
    array_push($penguins, new Penguin("Emperor Penguin", "Aptenodytes forsteri", "fish and squid", "The Emperor Penguin is a bird of extremes in just about every way. It breeds during the Antarctic winter and exhibits many adaptations to the extreme cold that these birds experience when breeding.", "http://www.penguinworld.com/types/emperor_files/emperorl-2.jpg",4 ));
    array_push($penguins, new Penguin("Erect-crested Penguin", "Eudyptes sclateri", "krill and squid", "A little-known rather bizarre bird with a limited breeding distribution in a very isolated part the world.", "http://www.penguinworld.com/types/erect_files/erectl-2.jpg",5 ));
    array_push($penguins, new Penguin("Fiordland Penguin", "Eudyptes pachyrhynchus", "fish and squid", "The Fiordland Penguin lives in the temperate rainforest of the southwest coast of the South Island and Stewart Island, New Zealand, where it is endemic.", "http://www.penguinworld.com/types/fiordland_files/fiordlandl-2.jpg", 6));
    array_push($penguins, new Penguin("Galapagos Penguin", "Spheniscus mendiculus", "small fish", "The northernmost of all penguins, Galapagos Penguins breed right on the equator. Populations fluctuate heavily under the influence of El Niño to a degree that the future survival of the species is endangered.", "http://www.penguinworld.com/types/galapagos_files/galapagosl-2.jpg", 7));
    array_push($penguins, new Penguin("Gentoo Penguin", "Pygoscelis papua", "krill and fish", "This is the most northern penguin of this genus and, in many other respects, the odd one out. In contrast to Chinstrap and Adelie Penguins, some Gentoo Penguins can be found around their breeding colonies all year round and they forage much closer inshore than the other two Pygoscelis species.", "http://www.penguinworld.com/types/gentoo_files/gentool-2.jpg", 8));
    array_push($penguins, new Penguin("King Penguin", "Aptenodytes patagonicus", "fish, some squid", "No other bird has a longer breeding cycle than King Penguins. They take 14 to 16 months to fledge a single chick. During the winter, chicks may be left to fast for from one to five months (May to September/October). Adults can rear a maximum of only two chicks every three years.", "http://www.penguinworld.com/types/king_files/kingl-3-2.jpg", 9));
    array_push($penguins, new Penguin("Little Penguin", "Eudyptula minor", "small fish", "The world’s smallest penguin (also known as Little Blue, Blue and Fairy Penguin).", "http://www.penguinworld.com/types/little_files/littlel2-2.jpg", 10));
    array_push($penguins, new Penguin("Macaroni Penguin", "Eudyptes chrysolophus", "krill", "This is probably the most abundant of all penguins in terms of total numbers. Brood reduction is taken to an extreme by this species. The Royal Penguin (Eudyptes chrysolophus schlegeli), a white-faced variant, is treated as a subspecies of Macaroni Penguin here, but others accord the Royal penguin full species status.", "http://www.penguinworld.com/types/macaroni_files/macaroni-002850029.jpg", 11));
    array_push($penguins, new Penguin("Magellanic Penguin", "Spheniscus magellanicus", "small fish", "Similar to African Penguin (to which it is very closely related), but breeding on the opposite side of the Atlantic. It is also the only migratory, offshore-foraging species in this genus.", "http://www.penguinworld.com/types/magellanic_files/magellanicl-3.jpg", 12));
    array_push($penguins, new Penguin("Rockhopper Penguin", "Eudyptes chrysocome", "krill, fish and squid", "Breeding in sometimes-large colonies throughout the sub-Antarctic. Smaller than its congeners, but no less aggressive. There is some evidence that the Northern Rockhopper or Moseley’s Penguin is deserving of separate species status. Whatever, the Northern Rockhopper and Southern Rockhopper are clearly closely related and much of what applies to one probably holds for the other, but actual data are still scarce.", "http://www.penguinworld.com/types/rockhopper_files/rockhopperl-2.jpg", 13));
    array_push($penguins, new Penguin("Royal Penguin", "Eudyptes schlegeli ", "krill", "The Royal Penguin is treated as a separate penguin species (Eudyptes schlegeli) by some. However, other authorities highlight evidence from DNA, morphology and behaviour that points to Royal Penguins being a white-faced variant (Eudyptes chrysolophus schlegeli) of Macaroni Penguins.", "http://www.penguinworld.com/types/royal_files/macaronil-2.jpg", 14));
    array_push($penguins, new Penguin("Royal Penguin", "Pygoscelis adeliae", "krill", "The Royal Penguin is treated as a separate penguin species (Eudyptes schlegeli) by some. However, other authorities highlight evidence from DNA, morphology and behaviour that points to Royal Penguins being a white-faced variant (Eudyptes chrysolophus schlegeli) of Macaroni Penguins.", "http://www.penguinworld.com/types/royal_files/macaronil-2.jpg", 15));
    array_push($penguins, new Penguin("Snares Penguin", "Eudyptes robustus ", "krill, squid and fish", "Similar in many respects to Fiordland Penguin but endemic to the Snares Islands, which are about 100 km south of the nearest Fiordland Penguin breeding sites. With its breeding range confined to the just over 300 ha of the Snares group, it has the most restricted distribution of all penguins.", "http://www.penguinworld.com/types/snares_files/snares-2.jpg", 16));
    array_push($penguins, new Penguin("Yellow-eyed Penguin", "Megadyptes antipodes", "fish and squid", "The Yellow-eyed Penguin is often referred to as the rarest penguin in the world, although, unfortunately, there are others that could lay claim to that crown too: especially the Galapagos and Fiordland Penguins.", "http://www.penguinworld.com/types/yellow_files/yellowl-2.jpg", 17));
    
    print json_encode($penguins);    
?>
